version: "3.8"

services:
  backend:
    image: ghcr.io/organizacionp6/clinica-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clinica_veterinaria
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
    depends_on:
      - db

  frontend:
    image: ghcr.io/organizacionp6/clinica-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: clinica_veterinaria
    ports:
      - "5432:5432"
